# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["projects", "experience"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2025
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "üë®‚Äçüíª"
subtitle = "Computer Science Student @ University of Pittsburgh"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "remysedlak/remy-portfolio-hugo"
repoID = "R_kgDOQ4scgQ"
category = "Announcements"
categoryID = "DIC_kwDOQ4scgc4C04tK"
mapping = "pathname"
theme = "preferred_color_scheme"
lang = "en"
